<a href="https://colab.research.google.com/github/kjgeetasri/AIML-COLAB/blob/main/Randam_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Model Sample Data - Retail Inventory.xlsx to Model Sample Data - Retail Inventory (1).xlsx

In [4]:
import pandas as pd
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

In [5]:
import pandas as pd

# The file 'Model Sample Data - Retail Inventory.xlsx' was uploaded.
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

display(df.head())

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469,30,47,83,119,NDS,75,63.75,...,30.18227,0,60,55,500.0,147,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72,136,20,46,72,NDS,101,40.4,...,8.653497,1.35,60,57,600.0,6,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366,48,49,89,128,NDS,89,75.65,...,25.583349,0,60,56,1250.0,90,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393,96,35,63,90,UDS,1907.5,1750,...,26.826563,1.62,60,55,720.0,94,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121,23,49,80,111,NDS,45,38.25,...,12.23189,0,60,59,500.0,79,PASTRY,NaN,NaN,NaN

In [6]:
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

In [7]:
display(df.describe())

,Unnamed: 16,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.0000,9.000000,9.000000
mean,795.0000,3.333333,0.333333
std,361.1834,2.500000,0.250000
min,400.0000,1.000000,0.100000
25%,500.0000,1.000000,0.100000
50%,660.0000,4.000000,0.400000
75%,1000.0000,5.000000,0.500000
max,1500.0000,8.000000,0.800000

In [9]:
import os
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [10]:
import os
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [11]:
print("Missing values in each column:\n")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            3
Beginning Inventory (Bipi, pc)                                              3
Lower Maintaining Inventory Level (LMILpi, pc)                              3
Expected Maintaining Inventory Level (EMILpi, pc)                           3
Upper Maintaining Inventory Level (UMILpi, pc)                              3
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  3
cost (cp, Php/pc)                                                           3
disposal cost (disppi, Php/pc)                                              3
transport cost (tpi, Php/pc)                                                3
warehouse holding cost (wpi, Php/pc)                                        3
transshipment cost (tspi, Php/pc)                                           3
ordering cost (copi, Php/pc)                                                3
Weight per unit of product (g)                                              3
Unnamed: 16                                                                 5
Sales (units)                                                               3
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [12]:
import os
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [13]:
import numpy as np

In [14]:
print("Descriptive statistics for numerical columns after conversion:")
display(df.describe())

Descriptive statistics for numerical columns after conversion:

,Unnamed: 16,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.0000,9.000000,9.000000
mean,795.0000,3.333333,0.333333
std,361.1834,2.500000,0.250000
min,400.0000,1.000000,0.100000
25%,500.0000,1.000000,0.100000
50%,660.0000,4.000000,0.400000
75%,1000.0000,5.000000,0.500000
max,1500.0000,8.000000,0.800000

In [15]:
from google.colab import files
uploaded = files.upload()

Saving Model Sample Data - Retail Inventory.xlsx to Model Sample Data - Retail Inventory (2).xlsx

In [16]:
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'Model Sample Data - Retail Inventory (2).xlsx', 'sample_data']

In [17]:
print("Missing values in each column:")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            3
Beginning Inventory (Bipi, pc)                                              3
Lower Maintaining Inventory Level (LMILpi, pc)                              3
Expected Maintaining Inventory Level (EMILpi, pc)                           3
Upper Maintaining Inventory Level (UMILpi, pc)                              3
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  3
cost (cp, Php/pc)                                                           3
disposal cost (disppi, Php/pc)                                              3
transport cost (tpi, Php/pc)                                                3
warehouse holding cost (wpi, Php/pc)                                        3
transshipment cost (tspi, Php/pc)                                           3
ordering cost (copi, Php/pc)                                                3
Weight per unit of product (g)                                              3
Unnamed: 16                                                                 5
Sales (units)                                                               3
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [18]:
print("Missing values in each column:")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            3
Beginning Inventory (Bipi, pc)                                              3
Lower Maintaining Inventory Level (LMILpi, pc)                              3
Expected Maintaining Inventory Level (EMILpi, pc)                           3
Upper Maintaining Inventory Level (UMILpi, pc)                              3
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  3
cost (cp, Php/pc)                                                           3
disposal cost (disppi, Php/pc)                                              3
transport cost (tpi, Php/pc)                                                3
warehouse holding cost (wpi, Php/pc)                                        3
transshipment cost (tspi, Php/pc)                                           3
ordering cost (copi, Php/pc)                                                3
Weight per unit of product (g)                                              3
Unnamed: 16                                                                 5
Sales (units)                                                               3
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [19]:
print("First 5 rows of the DataFrame:")
display(df.head())

First 5 rows of the DataFrame:

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469,30,47,83,119,NDS,75,63.75,...,30.18227,0,60,55,500.0,147,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72,136,20,46,72,NDS,101,40.4,...,8.653497,1.35,60,57,600.0,6,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366,48,49,89,128,NDS,89,75.65,...,25.583349,0,60,56,1250.0,90,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393,96,35,63,90,UDS,1907.5,1750,...,26.826563,1.62,60,55,720.0,94,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121,23,49,80,111,NDS,45,38.25,...,12.23189,0,60,59,500.0,79,PASTRY,NaN,NaN,NaN

In [20]:
import os
import zipfile
import pandas as pd

In [21]:
print("First 5 rows of the DataFrame:")
display(df.head())

First 5 rows of the DataFrame:

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469,30,47,83,119,NDS,75,63.75,...,30.18227,0,60,55,500.0,147,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72,136,20,46,72,NDS,101,40.4,...,8.653497,1.35,60,57,600.0,6,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366,48,49,89,128,NDS,89,75.65,...,25.583349,0,60,56,1250.0,90,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393,96,35,63,90,UDS,1907.5,1750,...,26.826563,1.62,60,55,720.0,94,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121,23,49,80,111,NDS,45,38.25,...,12.23189,0,60,59,500.0,79,PASTRY,NaN,NaN,NaN

In [22]:
print("DataFrame Info (data types and non-null counts):")
df.info()

DataFrame Info (data types and non-null counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 22 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   Store Location (i)                                                       17 non-null     object
 1   Product                                                                  32 non-null     object
 2   Volume per unit of product (cm3)                                         32 non-null     object
 3   Beginning Inventory (Bipi, pc)                                           32 non-null     object
 4   Lower Maintaining Inventory Level (LMILpi, pc)                           32 non-null     object
 5   Expected Maintaining Inventory Level (EMILpi, pc)                        32 non-null     object
 6   Upper Maintaining Inventory Level (UMILpi, pc)                           32 non-null     object
 7   Product category (from Phase 1)                                          32 non-null     object
 8   selling price (sp, Php/pc)                                               32 non-null     object
 9   cost (cp, Php/pc)                                                        32 non-null     object
 10  disposal cost (disppi, Php/pc)                                           32 non-null     object
 11  transport cost (tpi, Php/pc)                                             32 non-null     object
 12  warehouse holding cost (wpi, Php/pc)                                     32 non-null     object
 13  transshipment cost (tspi, Php/pc)                                        32 non-null     object
 14  ordering cost (copi, Php/pc)                                             32 non-null     object
 15  Weight per unit of product (g)                                           32 non-null     object
 16  Unnamed: 16                                                              30 non-null     float64
 17  Sales (units)                                                            32 non-null     object
 18  Product Reference                                                        32 non-null     object
 19  Unnamed: 19                                                              9 non-null      object
 20  REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26  9 non-null      float64
 21  Unnamed: 21                                                              9 non-null      float64
dtypes: float64(3), object(19)
memory usage: 6.1+ KB

In [23]:
print("Descriptive statistics for numerical columns:")
display(df.describe())

Descriptive statistics for numerical columns:

,Unnamed: 16,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.0000,9.000000,9.000000
mean,795.0000,3.333333,0.333333
std,361.1834,2.500000,0.250000
min,400.0000,1.000000,0.100000
25%,500.0000,1.000000,0.100000
50%,660.0000,4.000000,0.400000
75%,1000.0000,5.000000,0.500000
max,1500.0000,8.000000,0.800000